run:
  timeout: 2m
  tests: true
  skip-dirs:
    - vendor

output:
  formats:
    - github-actions

linters:
  enable:
    - govet
    - errcheck
    - revive
    - staticcheck
    - unused

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning
      - name: unused-parameter
        severity: warning

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck