version: '3.8'

services:
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  payment-processor:
    build:
      context: ./payment-processor
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_QUEUE=payment-events
    depends_on:
      - redis

volumes:
  redis-data:
  pgdata: