version: '3.8'

services:
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  payment-receiver:
    build:
      context: ./payment-receiver
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_QUEUE=payment-events
    depends_on:
      - redis
    restart: on-failure

  payment-processor:
    build:
      context: ./payment-processor
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_QUEUE=payment-events
    depends_on:
      - redis

volumes:
  redis-data: