name: Dispatcher CI

on:
  push:
    paths:
      - 'payment-receiver/cmd/dispatcher/**'
      - 'payment-receiver/domain/**'
      - 'payment-receiver/usecase/**'
      - 'payment-receiver/repository/**'
      - '.github/workflows/ci-dispatcher.yml'
  pull_request:
    paths:
      - 'payment-receiver/cmd/dispatcher/**'
      - 'payment-receiver/domain/**'
      - 'payment-receiver/usecase/**'
      - 'payment-receiver/repository/**'
      - '.github/workflows/ci-dispatcher.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: payment-receiver

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: payment-receiver/go.mod
          cache: false

      - name: Cache Go modules and tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: go-cache-${{ runner.os }}-

      - name: Install tools
        run: |
          go install github.com/segmentio/golines@v0.11.0
          go install golang.org/x/tools/cmd/goimports@v0.20.0
          go install mvdan.cc/gofumpt@v0.5.0
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Format check
        run: make fmt

      - name: Lint
        run: make lint

      - name: Build dispatcher
        run: make build-dispatcher

      - name: Run tests
        run: make test-unit
