name: Payment Processor CI

on:
  push:
    paths:
      - 'payment-processor/**'
      - '.github/workflows/ci-processor.yml'
  pull_request:
    paths:
      - 'payment-processor/**'
      - '.github/workflows/ci-processor.yml'

jobs:
  processor-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: payment-processor

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: payment-processor

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
        working-directory: payment-processor