name: Webhook Receiver CI

on:
  push:
    paths:
      - 'payment-receiver/**'
      - '.github/workflows/ci-receiver.yml'
  pull_request:
    paths:
      - 'payment-receiver/**'
      - '.github/workflows/ci-receiver.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: payment-receiver/go.mod
          cache: false # 明示的に無効化

      - name: Set up Go environment variables
        run: echo "GOBIN=${{ github.workspace }}/bin" >> $GITHUB_ENV

      - name: Cache Go modules and tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ${{ github.workspace }}/bin
          key: go-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-cache-${{ runner.os }}-

      - name: Install dependencies
        run: go mod download
        working-directory: payment-receiver

      - name: Install tools
        run: |
          go install github.com/segmentio/golines@latest
          go install golang.org/x/tools/cmd/goimports@latest
          go install mvdan.cc/gofumpt@latest

      - name: Add tools to PATH
        run: echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Format check
        run: |
          gofumpt -l . > gofumpt-diff.txt
          goimports -l . > goimports-diff.txt
          golines --max-len=100 -l . > golines-diff.txt

          cat gofumpt-diff.txt goimports-diff.txt golines-diff.txt

          if [ -s gofumpt-diff.txt ] || [ -s goimports-diff.txt ] || [ -s golines-diff.txt ]; then
            echo "::error::Formatting issues found. Please run 'make fmt' and commit the changes."
            exit 1
          fi
        working-directory: payment-receiver
